# Generated by Django 3.2.16 on 2023-03-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraccount_selleracceptedterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
