# Generated by Django 3.2.16 on 2023-02-28 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('from_address', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('tx_hash', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('private_key', models.TextField(unique=True)),
                ('polygon_address', models.CharField(max_length=255, unique=True)),
                ('polygon_private_key', models.TextField(unique=True)),
                ('cardano_address', models.CharField(max_length=255, unique=True)),
                ('cardano_private_key', models.TextField(unique=True)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('product_sales', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('course_sales', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('total_transfered', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('save_card', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions', models.ManyToManyField(blank=True, to='wallet.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
