# Generated by Django 3.2.16 on 2023-02-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='cardano_address',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='cardano_private_key',
        ),
    ]
